const lightest = require('../lightest.js');
const staticAliases = require('../staticAliases.js');
const actionbutton-color = exports;
exports["text-color"] = lightest["colorAliases"].["text-color-disabled"];
exports["icon-color"] = lightest["colorAliases"].["icon-color-disabled"];
exports["border-size"] = staticAliases["border-size-thin"];
exports["background-color"] = lightest["gray-200"];
exports["border-color"] = lightest["gray-200"];
exports["hold-icon-color"] = lightest["colorAliases"].["icon-color-selected-focus"];
