const dimensionGlobals = require('../dimensionGlobals.js');
const medium = require('../medium.js');
const dragbar = exports;
exports["handle-width"] = dimensionGlobals["size-25"];
exports["gripper-width"] = dimensionGlobals["size-50"];
exports["gripper-height"] = dimensionGlobals["size-200"];
exports["gripper-border-width-vertical"] = "4px";
exports["gripper-border-width-horizontal"] = "3px";
exports["gripper-border-radius"] = medium["dimensionAliases"].["border-radius-small"];
